### ISSUE TITLE
WP Smush "Automatic Smush uploaded image" not working when DOS plugin is active.

### ISSUE THREAD

**Issue by Dibbyo456** [keeross/DigitalOcean-Spaces-Sync#10]
**Issue**: [WP Smush](https://wordpress.org/plugins/wp-smushit/) can't smush the uploaded image when DOS Plugin is active.

**Reason:** Probably because before WP Smush can smush the image, DOS takes the images to Spaces.

**Fix:** Although I have found a patch for it, but not sure if it's a good one thus creating the issue here, so you can take a look.

If we change this (**dos_class.php, Line 77**)

```php
add_filter('wp_generate_attachment_metadata', array($this, 'filter_wp_generate_attachment_metadata'), 10, 1);
```

to this

```php
add_filter('wp_update_attachment_metadata', array($this, 'filter_wp_generate_attachment_metadata'), 20, 1);
```

Everything works perfectly. Is there a better way to do this?

You also wanna check ("wp-smushit\lib\class-wp-smush.php", Line 173)

**P.S** - I have **Store files only in the cloud** & **Delete file from cloud storage** active.

**Comment by keeross** [comment]
Yeah, that should work fine, changing 10 to 20, we change priority of hook, so it will run after all the other. Will add this today.

**Comment by Dibbyo456** [comment]
> Yeah, that should work fine, changing 10 to 20, we change priority of hook, so it will run after all the other. Will add this today.

Not just priority, I changed `wp_generate_attachment_metadata` to `wp_update_attachment_metadata` because WP Smush automatically smush the images when the `wp_update_attachment_metadata` filter is triggered.

You can find the filter in "**wp-smushit\lib\class-wp-smush.php**", **Line 173**.

**Comment by keeross** [comment]
Updated plugin, looks like it is working now even with Image Editor.
