### ISSUE TITLE
Error when testing DO Spaces connection using defined constant

### ISSUE THREAD

**Issue by mscalessio** [keeross/DigitalOcean-Spaces-Sync#13]
Hi,
I'm trying to test the connection with my DO Spaces container using defined constant but I got this error: `Connection is not established. : Credentials must be an instance of Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false.`

Also while debugging I found that weird thing:
<img width="332" alt="schermata 2018-10-26 alle 00 00 35" src="https://user-images.githubusercontent.com/4687670/47533169-0d60e680-d8b3-11e8-910d-5f965deabfa5.png">
<img width="329" alt="schermata 2018-10-26 alle 00 09 21" src="https://user-images.githubusercontent.com/4687670/47533356-ad1e7480-d8b3-11e8-90b0-fa28ea4c74b2.png">

It seems that `key` and `secret` is not initialized.

**Comment by virusnac** [comment]
When I try to run a connection test, I get this error:
Connection is not established. : Invalid configuration value provided for "endpoint". Expected string, but got bool(false) endpoint: (string) The full URI of the webservice. This is only required when connecting to a custom endpoint (e.g., a local version of S3).

**Comment by keeross** [comment]
Should be fixed in 2.0.5

**Comment by virusnac** [comment]
Can confirm it is fixed.

**Comment by dauledk** [comment]
I just received this error again, with version 2.0.5:

```
Connection is not established. : Invalid configuration value provided for "endpoint".
Expected string, but got bool(false) endpoint: (string) The full URI of the webservice.
This is only required when connecting to a custom endpoint (e.g., a local version of S3).
```

I provided the following values: 

<img width="475" alt="screenshot 2018-11-09 at 19 38 11" src="https://user-images.githubusercontent.com/9967422/48262972-13c89400-e457-11e8-9935-c84b982a86a5.png">

**Comment by maximilliangeorge** [comment]
> I just received this error again, with version `2.0.5`
> 
> ```
> Connection is not established. : Invalid configuration value provided for "endpoint".
> Expected string, but got bool(false) endpoint: (string) The full URI of the webservice.
> This is only required when connecting to a custom endpoint (e.g., a local version of S3).
> ```
> I provided the following values:
> 
> <img alt="screenshot 2018-11-09 at 19 38 11" width="475" src="https://user-images.githubusercontent.com/9967422/48262972-13c89400-e457-11e8-9935-c84b982a86a5.png">
> 
> **Update**
> Just did a file upload test, and it actually works. Only the `test connection` just failing 😊

I'm having the same issue.

**Comment by devsatwik** [comment]
This is because you must save the settings before checking the connection
had the same prob , fixed !!

**Comment by waituk** [comment]
> This is because you must save the settings before checking the connection
> had the same prob , fixed !!

Yup - indeed. Save settings and then recheck works!
