### ISSUE TITLE
Can't upload new images or install plugins/themes

### ISSUE THREAD

**Issue by virusnac** [keeross/DigitalOcean-Spaces-Sync#16]
Hi, I have a weird behavior after updating the plugin from 1.1.0 to current version. Besides that I can not run a test connection, which I believe was already reported, I cannot upload new images or install a new plugin/theme.

I have 2 sites running on nginx 1.12.2 server with PHP 5.5.9-1ubuntu4.26 (cli) (built: Sep 17 2018 13:46:30) with Zend OPcache v7.0.3 and I get this error:

2018/10/26 05:05:19 [error] 834#834: *60775 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot instantiate abstract class Aws\ClientSideMonitoring\AbstractMonitoringMiddleware in .../wp-content/plugins/do-spaces-sync/vendor/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddlewa$

Deactivating the plugin allows me to upload plugins/themes/images with no issues.

Note that my second site is a multisite and the upload works fine for all scenarios.

**Comment by keeross** [comment]
Updated AWS-SDK, could you please update to 2.0.5 and report if it is fixed or not.

**Comment by virusnac** [comment]
Thanks, indeed, after update to 2.0.5 I can install/update both plugins and themes. 

However, I have run into some different issues which I will report separately. 

Thanks again!
