### ISSUE TITLE
Uploads error using plugin

### ISSUE THREAD

**Issue by frappacchio** [keeross/DigitalOcean-Spaces-Sync#19]
Hi, i'm getting 2 errors trying this plugin:
the first one is about this warning:
`Deprecated: Non-static method DOS_Filesystem::get_instance() should not be called statically in /var/www/html/wp-content/plugins/do-spaces-sync/dos_class.php on line 273` 

The second one is that the plugin creates folders starting from root:
`var/www/html/...`
If i use the web interface from Digitalocean i cannot access to the www folder because it blocks me.
How can i upload media in the right way?
Thanks,
Francesco

**Comment by SHoogland** [comment]
Hi, @frappacchio I fixed the warning in #20 but there is not much activity here. How are you going with your fork?
