### ISSUE TITLE
Mask/Filter Doesn't Seem To Be Working

### ISSUE THREAD

**Issue by ideasandpixels** [keeross/DigitalOcean-Spaces-Sync#2]
I'm having a major conflict with Elementor with this plugin related to Masks/Filters not working. This plugin works great for Spaces storage, but Elementor automatically creates CSS files for it's pages and these CSS files obviously don't use the standard media upload functionality on creation, so they don't get uploaded/added to Spaces. This causes all CSS files generated by Elementor to fail, because they are not in the Spaces space.

That's fine, and a workaround would be to add the specific file types to the DOS Filters, leaving out *.css, which I've done. But any time CSS files are linked, it's still trying to use the Spaces URL. It seems to be completely ignoring my filters.

Here are my settings for the filter field: \*.jpg,\*.png,\*.pdf

Perhaps I'm misunderstanding what the Filter is for. If it's just to control which types of files get uploaded to Spaces, I think a good, simple addition would be to add another Filter for determining what kinds of files should look on Spaces and which should look locally.

**Comment by Dibbyo456** [comment]
Yup. Filemask does not work.

**Comment by CasperEngl** [comment]
It's happening for me with DO Spaces Sync 2.0.2.1 and Elementor 2.2.5 + Elementor Pro 2.1.10
My regex is `/^.*\.(jpg|jpeg|png|gif|ico|svg|pdf|doc|docx|ppt|pptx|pps|ppsx|odt|xls|xlsx|psd|mp3|m4a|ogg|wav|mp4|m4v|mov|wmw|avi|mpg|ogv|3gp|3g2)$/i`
The regex is basically just a copy of all default allowed files in WordPress upload with the exception of SVG which I've added.

`https://domain.tld/wp-content/uploads/elementor/css/*.css` files are rewritten to `https://ams3.digitaloceanspaces.com/domain.tld/elementor/css/*.css`

Is the regex being applied on URL rewrites on the frontend?

**Comment by aryeharmon** [comment]
still an issue
