### ISSUE TITLE
Plugin Uploads to DO and not installed

### ISSUE THREAD

**Issue by NCHostmaster** [keeross/DigitalOcean-Spaces-Sync#21]
I have to upload a specific plugin for our site and when I do I get the invalid URL error. Looking through our DO spaces, the plugin is residing in DO Spaces. I looked at all the issues, and cannot account for this issue. It is similar to Media Cloud plugin option for treating all non-image files as uploads.

**Comment by keeross** [comment]
Not really, you have to add `.zip` files to ignore list, in order to proceed, kinda like this: 
`/^.*\.(zip|rar)$/i`

**Comment by NCHostmaster** [comment]
That was the issue. The previous person did not add the /^.*\ when they set up the plugin.
  

  
  

  
  
>
