### ISSUE TITLE
Error when Test connection 

### ISSUE THREAD

**Issue by tansautn** [keeross/DigitalOcean-Spaces-Sync#26]
after installed plugin
while all options is still default as it inserted when install hook ran

goto the setting page , input storage connection detail , submit "**TEST CONNECTION**". We'll get error bellow.
![chrome_2019-08-08_09-00-48](https://user-images.githubusercontent.com/6666271/62672830-5a3b2700-b9c6-11e9-95cc-aeeee08de166.png)

Debuging in few minutes , i've catched the error. This issue came because when clicking "TEST CONNECTION" and doing ajax post , all of the post data will be ignored. The values using in constructor of League\Flysystem\AwsS3v3\AwsS3Adapter is invalid (in this case it came by calling get_option function).

Then i've made some changes in DOS::test_connection. It's working now. Here is body of method test_connection() now.
![phpstorm64_2019-08-08_10-09-56](https://user-images.githubusercontent.com/6666271/62672853-6a530680-b9c6-11e9-8880-cc03665a899b.png)

Cause it's small changes , so i will posted as the issue, sorry for no pull request (i'm still new with wordpress also)
Code : 

          public function test_connection () {
            if($_SERVER['REQUEST_METHOD'] === 'POST'){
                $postData = $_POST;
                $keys = ['key' => 'dos_key','secret' => 'dos_secret','endpoint' => 'dos_endpoint','container' => 'dos_container'];
                foreach ($keys as $prop => $key) {
                    if(isset($postData[$key])){
                        $this->$prop = $postData[$key];
                    }
                }
            }
            try {
    
              $filesystem = DOS_Filesystem::get_instance($this->key, $this->secret, $this->container, $this->endpoint);
              $filesystem->write('test.txt', 'test');
              $filesystem->delete('test.txt');
              // $exists = $filesystem->has('photo.jpg');
    
              $this->show_message(__('Connection is successfully established. Save the settings.', 'dos'));
              exit();
    
            } catch (Exception $e) {
    
              $this->show_message( __('Connection is not established.','dos') . ' : ' . $e->getMessage() . ($e->getCode() == 0 ? '' : ' - ' . $e->getCode() ), true);
              exit();
    
            }
    
          }

Hope this will help plugin's developers to improve this. Sorry for my bad english.

**Comment by keeross** [comment]
Thank you, will test it soon!
