### ISSUE TITLE
Assets & Images on Digitalocean Spaces

### ISSUE THREAD

**Issue by ismaelhaider** [keeross/DigitalOcean-Spaces-Sync#28]
I followed the article on Digitalocean tutorial for DO Spaces Sync plugin, I configured and its uploading images too but on my site when i am viewing images url it shows local url , but not for CDN.
How to fix this?
2) Please help me for assets , how i can sync static,JS,CSS to spaces ? currenlty its only uplaoding images

**Comment by yongzhenlow** [comment]
@ismaelhaider If you wish to serve your media files from your spaces, [configure a CDN](https://blog.digitalocean.com/custom-subdomains-for-spaces-cdn-endpoints/) and enter the Subdomain endpoint into the `Full URL-path to files:` field. 

Alternatively, you can simply use the default Origin endpoint `https://<youspacesname>.<region>.digitaloceanspaces.com`.

**Comment by keeross** [comment]
Sorry, can't help you with assets, this plugin works with Media Library only
