### ISSUE TITLE
$first_file undefined in settings_page.php

### ISSUE THREAD

**Issue by alexandre-tobia** [keeross/DigitalOcean-Spaces-Sync#3]
Hi,

On the settings page, i got this error

```php
notice: Undefined variable: first_file in .../do-spaces-sync/code/settings_page.php on line 190
```

Do you know how to solve this?

PHP Version: 7.1.16
WP Version: 4.9.5

Thanks for your work :-)

**Comment by alexandre-tobia** [comment]
@keeross  Any clues ?

**Comment by natefoundry** [comment]
I'm seeing this in my install too. I looked at the file where it was failing and it's just a variable used for the instructions for one of the fields but doesn't affect saving the plugin settings.

However, it's a little jarring to see and should be fixed.

WP Version: 4.9.5
PHP Version : 7.2.5

**Comment by jfarthing84** [comment]
Just encountered this. The variable is not declared anywhere...

**Comment by keeross** [comment]
Fixed, will be released in a week.
