### ISSUE TITLE
Will wordpress 5.3 break DigitalOcean Spaces Sync?

### ISSUE THREAD

**Issue by opicron** [keeross/DigitalOcean-Spaces-Sync#32]
Quote from S3 Offload Media plugin:

> We realized just a few weeks ago that changes in WordPress 5.3 were going to break WP Offload Media in a bad way, so it’s been quite a scramble to fix the issues and get this release out before WordPress 5.3 drops this week. But we’ve done it and even managed to fit in a couple of thorough rounds of testing by pulling developers off other projects and putting in time in the evenings and weekends.

Is the wordpress 5.3 update something which will break DigitalOcean Spaces Sync too?

**Comment by keeross** [comment]
I've tested it just a few minutes ago, works fine, not sure about multisite, but overall works ok. Closing for now, feel free to reopen if any issue arises.
