### ISSUE TITLE
Since wordpress 5.3 wp_update_attachment_metadata is called on each generated file

### ISSUE THREAD

**Issue by opicron** [keeross/DigitalOcean-Spaces-Sync#34]
Since wordpress 5.3 wp_update_attachment_metadata is called on each generated file.

This means the upload of each generated media file is executed for each file. Meaning 6 media sizes are uploaded 6*6 times.

I noticed an immense slowdown since 5.3 and just now found out why ;).

An more thorough read about the subject:

https://make.wordpress.org/core/2019/11/05/use-of-the-wp_update_attachment_metadata-filter-as-upload-is-complete-hook/

Please change the filter to use: wp_generate_attachment_metadata instead.

I would make an pull request, but seeing the last one is not pulled in I refrain :P.

**Comment by keeross** [comment]
Fixed in https://github.com/keeross/DigitalOcean-Spaces-Sync/releases/tag/v2.2.1
