### ISSUE TITLE
Empty regular expression - warning

### ISSUE THREAD

**Issue by derpoho** [keeross/DigitalOcean-Spaces-Sync#4]
Hey,

the `preg_match` here https://github.com/keeross/DigitalOcean-Spaces-Sync/blob/master/code.php#L243 causes an `preg_match(): Empty regular expression` warning if warnings are enabled and the filter is set to *.

Why is the regex checked there again? don't you do all the checks in `dos_check_for_sync`?

Maybe you can implement a solution around this warning.

**Comment by keeross** [comment]
Fixed in 2.0, currently testing it, will release in a week.
