### ISSUE TITLE
Cannot use "Store files only in the cloud and delete after successful upload" option with duplicate media file names

### ISSUE THREAD

**Issue by MrNghia123** [keeross/DigitalOcean-Spaces-Sync#5]
Hi,
Thanks for the plugin.
I need to use the "Store files only in the cloud and delete after successful upload" option.
It seems to work flawlessly when the media files being uploaded that have different file names. However the media files uploaded have duplicated names, the media files get overwritten in the DO space.
Some might argue that duplicated media names should overwritten files and the plugin is working the way it should be. However, without the use of this plugin, Wordpress works fine with duplicated media file names, as it seem to add a number to the file names to differentiate them. It does not overwrite the media.
- Wordpress way:
image.jpg
image-1.jpg
image-2.jpg

Otherwise the plugin seems to work. But the above issue make it not usable for my project.
Regards,
Nghia Huynh

**Comment by Dibbyo456** [comment]
Yes, I'm having the same issue. :/

**Comment by keeross** [comment]
Fixed in 2.0, testing it currently on my websites. Planning to release it in a week.

**Comment by Dibbyo456** [comment]
Oh my god.. I thought you were dead.. You came back after a long time.. 👍
