### ISSUE TITLE
Somewhere a link back to GitHub?

### ISSUE THREAD

**Issue by TerenceMilbourn** [keeross/DigitalOcean-Spaces-Sync#8]
Probably because you haven't (yet) made a clear link back from the plugin to here [https://github.com/keeross/DigitalOcean-Spaces-Sync/](https://github.com/keeross/DigitalOcean-Spaces-Sync/) somewhere on the [/wp-admin/options-general.php?page=do-spaces-sync%2Fcode.php](/wp-admin/options-general.php?page=do-spaces-sync%2Fcode.php) page, -- or if there is one I couldn't see it -- users will be reporting issues here [https://wordpress.org/support/plugin/do-spaces-sync](https://wordpress.org/support/plugin/do-spaces-sync) which is easier to find.

**Comment by keeross** [comment]
Just added some updates to files and setting page too, will release in a week.
