### ISSUE TITLE
Some console errors found

### ISSUE THREAD

**Issue by delythchandler** [keeross/DigitalOcean-Spaces-Sync#9]
Hi 
Looks like this plugin will be really useful, however there are still some bugs:
- do_logo.svg missing
- Found 2 elements with non-unique id #submit
Also, I can't find any reference to what the "DO Spaces Container:" is. I've set up the endpoint url but cannot see what needs to go in here?

Many thanks
Delyth

**Comment by keeross** [comment]
Thank you, fixed in 2.0.4
